apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: DB_USER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: DB_DATABASE
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
            subPath: postgres
      volumes:
        - name: postgres-data
          persistentVolumeClaim: 
            claimName: db-pvc
          
