apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: my-app
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  DB_USER: cG9zdGdyZXM=
  DB_DATABASE: cG9zdGdyZXM=
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWhfYiRuJi1sbmdmKHY4I3VAeTBkKXMjIWEqa2Y1ZjA3bG93aWt4aTdob2tecD1eY2hs
